### PR TITLE
Upscalers and lot of setting improve

### PR DESCRIPTION
**Pull request by GeorgLegato**
Prompts: 
Clear Button
Settings provide a Json-Code-editor for a default prompt, loaded on starting webui

new Tab:
Post Process
* UPSCALE *

Settings:
Define which models to take for txt2img (when no init image)
and which for img2img, for interpol images

### CODE REVIEW

**Comment by GeorgLegato** [comment]
image
image
image

**Comment by deklesen** [comment]
Small typo: its R-ESRGAN4x, not R-ERSGAn4x

**Comment by v8hid** [comment]
I'm trying to fix the Errors people getting, I will merge it as soon as that fixed.

**Comment by v8hid** [comment]
There is a problem with UI
image

**Comment by v8hid** [comment]
Moved to #41

**Pull request closed without merging**
