### PR TITLE
Allow for multiple generations per run

### PR DESCRIPTION
**Pull request by deklesen**
This PR implements multiple generations per run.

It's admittedly pretty hacky (only the last generated video is shown in the GUI), but might still be worth to merge.

### CODE REVIEW

**Comment by GeorgLegato** [comment]
this is the point I meant we should go for doing this as SCRIPT, means a script in the img2img section. 
when we add batchcount, select model, size, denoise, etc. we rebuild the img2img tab, right?

**Comment by v8hid** [comment]
Hi @deklesen, maybe it's better to ignore the video component and go with HTML5 video tag for showing the output.

**Comment by v8hid** [comment]
@GeorgLegato The Img2Img page is already too full of parameters, We want to keep the extension more organized and clean because people would have a better experience in this way.
I'm planning to remove a few redundant parameters such as Denoising strength, Inpaint Full Resolution, and padding. While these parameters can be helpful in the context of inpainting, they aren't necessary for our purposes and can add unnecessary confusion for users.

**Comment by GeorgLegato** [comment]
and here is an extension doing it via script
https://github.com/avantcontra/sd-webui-bug-infinite

**Comment by deklesen** [comment]
@GeorgLegato I like the current way, i.e. as a seperate tab, more.

**Comment by deklesen** [comment]
> Hi @deklesen, maybe it's better to ignore the video component and go with HTML5 video tag for showing the output.

Sorry, I won't implement this PR in a better way, feel free to close the PR if its too hacky as-is.

**Comment by v8hid** [comment]
Hello @deklesen! I noticed that you recently closed your pull request. I apologize for the delay in reviewing it, and I want to let you know that I value your contribution. I was planning to review it in action before merging it, but if you decided to close it for other reasons, please let me know. Thank you for your interest in contributing to the project!

**Comment by deklesen** [comment]
Hi v8hid, thanks, i think it got auto-deleted since i deleted the branch of my fork...

**Comment by GeorgLegato** [comment]
hehe, yeah keep your work, we will get this into consideration.
multirun makes sence, this the gallery is pretty useless, it always display THE ONE render

**Review by v8hid — APPROVED** [review]

**Pull request merged**
