### PR TITLE
Common prompt (incl json schema refactory)

### PR DESCRIPTION
**Pull request by GeorgLegato**
image

Look, "headers" is optional from now, it will be added by the readjson util
image

### CODE REVIEW

**Comment by v8hid** [comment]
It would be so great if you break it down to two parts.
1- Prompt Prefix
2- Prompt Suffix
This give user so much potential

**Comment by GeorgLegato** [comment]
> It would be so great if you break it down to two parts. 1- Prompt Prefix 2- Prompt Suffix This give user so much potential

this panel grows now even more, for reading prompt_prefix should be above table, then prompt_suffix below, then neg prompt. and in between button of the table... may need to relayou this tab

**Comment by v8hid** [comment]
@GeorgLegato You are absolutely right👍🏻

**Comment by GeorgLegato** [comment]
Prefix, Suffix added, 
Tooltips.
JSON schema improved.
main panel organised

image
image

**Review by v8hid — APPROVED** [review]

**Pull request merged**
